server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/linguabot
    username: myuser
    password: mypassword
    hikari:
      max-lifetime: 50000
  application:
    name: LinguaBot
  config:
    import: message.yaml
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: /db/changelog.xml
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}

  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    openfeign:
      client:
        config:
          ai:
            url: http://localhost:8082/ai/request
            loggerLevel: full

          wordSuggestion:
            loggerLevel: full
            url: http://localhost:8081/words

http:
  mini-app:
    "https://t.me/your_bot_username?start=your_start_parameter"
errorDetails:
  user-not-found:
    code: "USER_NOT_FOUND"
    message: "User not found."
    httpCode: 404
  incorrect-user:
    code: "INCORRECT_USER"
    message: "The user is invalid."
    httpCode: 400
  id-not-correct:
    code: "ID_NOT_CORRECT"
    message: "The not correct"
    http-code: 400
  default:
    code: "UNKNOWN ERROR"
    message: "The error is unknown."
    httpCode: 500
folder:
  select:
    "Выберите папку: "

topic:
  name:
    "addWord"
telegramBot:
  name:
    "EnglishBot"
  token:
    "7989664027:AAGv-d359PGiELNZqBSJCRJTgc5KPALZR-c"

cache:
  name: commands
  ttl:
    minutes: 15
