server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/linguabot
    username: myuser
    password: mypassword
    hikari:
      max-lifetime: 50000
  application:
    name: LinguaBot
  config:
    import: message.yaml
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: /db/changelog.xml
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}

  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    topics:
      notification: notification
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: notification
      bootstrap-servers: localhost:29092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        max.poll.interval.ms: 300000
        spring.json.trusted.packages: org.telegram.telegrambots.meta.api.methods.send, java.util, java.lang
  cloud:
    openfeign:
      client:
        config:
          ai:
            url: http://localhost:8082/ai/request
            loggerLevel: full

          wordSuggestion:
            loggerLevel: full
            url: http://localhost:8081/words

http:
  id:
    "?id="
  mini-app:
    "https://776e-178-70-97-175.ngrok-free.app"
errorDetails:
  user-not-found:
    code: "USER_NOT_FOUND"
    message: "User not found."
    httpCode: 404
  incorrect-user:
    code: "INCORRECT_USER"
    message: "The user is invalid."
    httpCode: 400
  id-not-correct:
    code: "ID_NOT_CORRECT"
    message: "The not correct"
    http-code: 400
  default:
    code: "UNKNOWN ERROR"
    message: "The error is unknown."
    httpCode: 500
folder:
  select:
    "Выберите папку: "

topic:
  add-word:
    "addWord"
  notification:
    "notification"
telegramBot:
  name:
    "EnglishBot"
  token:
    "7989664027:AAGv-d359PGiELNZqBSJCRJTgc5KPALZR-c"

repeat:
  times:
    - 20
    - 160
    - 1440
    - 4320
    - 10080

quantity-word: 2
quantity-repeat: 6

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

cache:
  name: commands
  ttl:
    minutes: 15
