server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/linguabot
    username: myuser
    password: mypassword
  application:
    name: LinguaBot

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: /db/changelog.xml
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
  cloud:
    openfeign:
      client:
        config:
          ai:
            url: https://gigachat.devices.sberbank.ru/api/v1/chat/completions
            loggerLevel: full

          aiAuth:

            url: https://ngw.devices.sberbank.ru:9443/api/v2/oauth



errorDetails:
  user-not-found:
    code: "USER_NOT_FOUND"
    message: "User not found."
    httpCode: 404
  incorrect-user:
    code: "INCORRECT_USER"
    message: "The user is invalid."
    httpCode: 400
  id-not-correct:
    code: "ID_NOT_CORRECT"
    message: "The not correct"
    http-code: 400
  default:
    code: "UNKNOWN ERROR"
    message: "The error is unknown."
    httpCode: 500

ai:
  url: 'https://ngw.devices.sberbank.ru:9443/api/v2/oauth'
  payload: 'scope=GIGACHAT_API_PERS'
  clientSecret: "1dd4675d-1f16-41a5-a711-f0b76a8676b6"
  authData: "MWRkNDY3NWQtMWYxNi00MWE1LWE3MTEtZjBiNzZhODY3NmI2OjY5MzUzNjZkLWVmYWEtNGY3OS1iOGFhLWEzN2UwYzBjZmU0Mg=="

